# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('acerca_de', models.TextField()),
                ('tipo_artista', models.CharField(choices=[('G', 'Grupo'), ('S', 'Solista')], max_length=50)),
                ('genero', models.CharField(choices=[('LA', 'Latina'), ('PO', 'Pop'), ('RO', 'Rock'), ('IA', 'Indie/Alternativa'), ('DA', 'Dance'), ('HH', 'Hip Hop'), ('RB', 'Rhythm and Blues'), ('CO', 'Country'), ('FA', 'Folk & Americana'), ('ME', 'Metal'), ('SO', 'Soul'), ('JA', 'Jazz'), ('BL', 'Blues'), ('PU', 'Punk'), ('FU', 'Funk'), ('CL', 'Clásica')], max_length=100)),
            ],
        ),
    ]
