# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170514_2214'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biblioteca',
            field=models.ManyToManyField(blank=True, to='music.Album'),
        ),
    ]
