# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artistas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('genero', models.CharField(choices=[('LA', 'Latina'), ('PO', 'Pop'), ('RO', 'Rock'), ('IA', 'Indie/Alternativa'), ('DA', 'Dance'), ('HH', 'Hip Hop'), ('RB', 'Rhythm and Blues'), ('CO', 'Country'), ('FA', 'Folk & Americana'), ('ME', 'Metal'), ('SO', 'Soul'), ('JA', 'Jazz'), ('BL', 'Blues'), ('PU', 'Punk'), ('FU', 'Funk'), ('CL', 'Clásica')], max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Artistas.Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('genero', models.CharField(choices=[('LA', 'Latina'), ('PO', 'Pop'), ('RO', 'Rock'), ('IA', 'Indie/Alternativa'), ('DA', 'Dance'), ('HH', 'Hip Hop'), ('RB', 'Rhythm and Blues'), ('CO', 'Country'), ('FA', 'Folk & Americana'), ('ME', 'Metal'), ('SO', 'Soul'), ('JA', 'Jazz'), ('BL', 'Blues'), ('PU', 'Punk'), ('FU', 'Funk'), ('CL', 'Clásica')], max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.Album')),
            ],
        ),
    ]
