# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='Artistas.Artista'),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='music.Album'),
        ),
    ]
