# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170514_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='url_cancion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
